FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python

RUN apt-get update && \
	apt-get install python3-pip && \
	apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip3 install rpi_ws281x paho-mqtt 

WORKDIR /usr/src/app

ENV INITSYSTEM on

COPY ./ .

CMD python3 LED_control.py
